# Generated by Django 5.0.7 on 2024-09-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casafeita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcompra',
            options={'verbose_name': 'Item Compra', 'verbose_name_plural': 'Itens da Compra'},
        ),
    ]
