# Generated by Django 5.0.7 on 2024-09-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casafeita', '0002_categoria_fabricante_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(blank=True, max_length=255, null=True)),
                ('ranking', models.IntegerField(max_length=1)),
                ('data', models.DateField()),
            ],
        ),
    ]
