# Generated by Django 5.0.7 on 2024-09-27 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casafeita', '0005_alter_avaliacao_data_alter_avaliacao_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='conteudo',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='ranking',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
