# Generated by Django 5.0.7 on 2024-09-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casafeita", "0006_rename_conteudo_avaliacao_descricao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cartao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(max_length=16)),
                ("nome", models.CharField(max_length=150)),
                ("validade", models.DateField()),
                ("cvv", models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=150)),
                ("numero", models.IntegerField(max_length=10)),
                ("complemento", models.CharField(max_length=150)),
                ("cep", models.IntegerField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="avaliacao",
            options={"verbose_name": "Avaliação", "verbose_name_plural": "Avaliações"},
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cartao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="casafeita.cartao",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="casafeita.endereco",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(max_length=10)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to="casafeita.compra",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="casafeita.produto",
                    ),
                ),
            ],
        ),
    ]
